
using pratices_angular_CURD.Dtos;
using pratices_angular_CURD.Model;
namespace pratices_angular_CURD.Dtos;
public static class StudentMappings
{
    public static Student ToEntity(this CreateStudentDto dto)
    {
        return new Student
        {
            // stdid is generated by DB
            stdname = dto.stdname,
            mobileno = dto.mobileno,
            email = dto.email,
            city = dto.city,
            state = dto.state,
            pincode = dto.pincode,
            address1 = dto.address1,
            address2 = dto.address2
        };
    }

    public static void UpdateEntity(Student entity, CreateStudentDto dto)
    {
        // Update only the fields that are meant to be edited via this DTO
        entity.stdname = dto.stdname;
        entity.mobileno = dto.mobileno;
        entity.email = dto.email;
        entity.city = dto.city;
        entity.state = dto.state;
        entity.pincode = dto.pincode;
        entity.address1 = dto.address1;
        entity.address2 = dto.address2;
    }


}
